/**
 * Database entity types for HTB Universe
 * These types correspond EXACTLY to the MySQL schema defined in agents/dbdump.sql
 */

// ============================================================================
// BETTER-AUTH TYPES (generated by better-auth CLI)
// ============================================================================

export interface User {
  id: string;
  name: string;
  email: string;
  emailVerified: boolean;
  image: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Session {
  id: string;
  expiresAt: Date;
  token: string;
  createdAt: Date;
  updatedAt: Date;
  ipAddress: string | null;
  userAgent: string | null;
  userId: string;
}

export interface Account {
  id: string;
  accountId: string;
  providerId: string;
  userId: string;
  accessToken: string | null;
  refreshToken: string | null;
  idToken: string | null;
  accessTokenExpiresAt: Date | null;
  refreshTokenExpiresAt: Date | null;
  scope: string | null;
  password: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Verification {
  id: string;
  identifier: string;
  value: string;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================================================
// CUSTOM USERS TABLE (Legacy/HTB-specific)
// ============================================================================

export type UserRole = "User" | "Admin";

export interface CustomUser {
  id: number;
  username: string | null;
  email: string | null;
  password: string | null;
  role: UserRole | null;
}

// ============================================================================
// HTB CORE ENTITIES - EXACT SCHEMA FROM dbdump.sql
// ============================================================================

export type MachineDifficulty = "Easy" | "Medium" | "Hard" | "Insane";
export type MachineOS = "Windows" | "Linux" | "Android" | "Solaris" | "OpenBSD" | "FreeBSD" | "Other";

export interface Machine {
  id: number;
  name: string | null;
  synopsis: string | null;
  difficulty: MachineDifficulty | null;
  os: MachineOS | null;
  url: string | null;
  image: string | null;
}

export type ModuleDifficulty = "Easy" | "Medium" | "Hard";

export interface Module {
  id: number;
  name: string | null;
  description: string | null;
  difficulty: ModuleDifficulty | null;
  url: string | null;
  image: string | null;
}

export type UnitType = "Article" | "Interactive";

export interface Unit {
  id: number;
  module_id: number;
  sequence_order: number | null;
  name: string | null;
  type: UnitType | null;
}

export interface Exam {
  id: number;
  name: string | null;
  logo: string | null;
}

export interface Vulnerability {
  id: number;
  name: string | null;
}

// NOTE: In the actual database schema (dbdump.sql), languages and areas of interest
// are stored directly as varchar(255) in their respective junction tables:
// - machine_languages.language (varchar)
// - machine_areas_of_interest.area_of_interest (varchar)
// They are NOT separate tables with id/name columns.
export type AreaOfInterest = string;
export type Language = string;

export interface VulnerabilityTool {
  id: number;
  name: string | null;
}

// ============================================================================
// RELATIONSHIP TABLES (Many-to-Many) - EXACT SCHEMA
// ============================================================================

export interface MachineVulnerability {
  machine_id: number;
  vulnerability_id: number;
}

export interface ModuleVulnerability {
  module_id: number;
  vulnerability_id: number;
}

export interface ModuleExam {
  module_id: number;
  exam_id: number;
}

export interface MachineModule {
  machine_id: number;
  module_id: number;
}

export interface MachineAreaOfInterest {
  machine_id: number;
  area_of_interest: string;
}

export interface MachineLanguage {
  machine_id: number;
  language: string;
}

// ============================================================================
// USER PROGRESS TABLES - EXACT SCHEMA
// ============================================================================

export interface UserMachine {
  user_id: number;
  machine_id: number;
  date: number | null; // Unix timestamp (bigint in MySQL)
  likes: boolean | null; // tinyint(1) in MySQL
}

export interface UserModule {
  user_id: number;
  module_id: number;
  date: number | null; // Unix timestamp (bigint in MySQL)
}

export interface UserExam {
  user_id: number;
  exam_id: number;
  date: number | null; // Unix timestamp (bigint in MySQL)
}

// ============================================================================
// USER SYNC TABLE (Bridge between better-auth and custom users)
// ============================================================================

export interface UserSync {
  auth_user_id: string; // UUID from better-auth user table
  custom_user_id: number; // Integer ID from custom users table
  username: string;
  email: string;
  role: UserRole;
  created_at: Date;
  updated_at: Date;
}

// ============================================================================
// EXTENDED TYPES WITH RELATIONSHIPS (for API responses)
// ============================================================================

export interface MachineWithDetails extends Machine {
  vulnerabilities?: Vulnerability[];
  modules?: Module[];
  languages?: string[]; // Array of language names
  areasOfInterest?: string[]; // Array of area of interest names
}

export interface ModuleWithDetails extends Module {
  units?: Unit[];
  vulnerabilities?: Vulnerability[];
  exams?: Exam[];
}

export interface ExamWithDetails extends Exam {
  modules?: Module[];
}

export interface UserWithProgress {
  user: CustomUser;
  completedMachines?: UserMachine[];
  completedModules?: UserModule[];
  completedExams?: UserExam[];
  stats?: {
    machinesCount: number;
    modulesCount: number;
    examsCount: number;
  };
}

// ============================================================================
// API REQUEST/RESPONSE TYPES
// ============================================================================

export interface MachineFilter {
  difficulty?: MachineDifficulty;
  os?: MachineOS;
  vulnerabilities?: number[]; // Array of vulnerability IDs
  modules?: number[]; // Array of module IDs
  search?: string;
  limit?: number;
  offset?: number;
}

export interface ModuleFilter {
  difficulty?: ModuleDifficulty;
  vulnerabilities?: number[]; // Array of vulnerability IDs
  exams?: number[]; // Array of exam IDs
  search?: string;
  limit?: number;
  offset?: number;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  limit: number;
  offset: number;
  hasMore: boolean;
}

// ============================================================================
// USER INPUT TYPES
// ============================================================================

/**
 * Input for creating a new user (combines both tables)
 */
export interface CreateUserInput {
  email: string;
  password: string;
  username: string;
  name: string;
  role?: UserRole;
}

/**
 * Input for updating user profile
 */
export interface UpdateUserInput {
  username?: string;
  name?: string;
  email?: string;
  image?: string;
}

// ============================================================================
// STATISTICS TYPES
// ============================================================================

export interface UserStatistics {
  totalMachines: number;
  totalModules: number;
  totalExams: number;
  machinesByDifficulty: {
    Easy: number;
    Medium: number;
    Hard: number;
    Insane: number;
  };
  modulesByDifficulty: {
    Easy: number;
    Medium: number;
    Hard: number;
  };
  recentActivity: Array<{
    type: "machine" | "module" | "exam";
    id: number;
    name: string;
    date: number;
  }>;
}

export interface GlobalStatistics {
  totalUsers: number;
  totalMachines: number;
  totalModules: number;
  totalExams: number;
  totalVulnerabilities: number;
  popularMachines: Array<{
    id: number;
    name: string;
    completions: number;
  }>;
  popularModules: Array<{
    id: number;
    name: string;
    completions: number;
  }>;
}
